name: release-please

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: nodecg

      - uses: actions/checkout@v3

      - run: echo "${{ toJSON(release.outputs) }}"


  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}

    steps:
      - uses: actions/checkout@v3

      - run: echo "${{ needs.release-please.outputs }}"
